# Generated by Django 6.0.6 on 2026-07-02 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='download_count',
        ),
    ]
