# Generated by Django 6.0.6 on 2026-07-03 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_remove_book_download_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bookfiles/')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB')], max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='books.book')),
            ],
            options={
                'unique_together': {('book', 'format')},
            },
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('book_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_history', to='files.bookfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
