# Generated by Django 6.0.6 on 2026-07-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadhistory',
            name='download_count',
        ),
        migrations.AddField(
            model_name='bookfile',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
